name: FlutterBuildAndRelease

on:
  push:
    branches: [ main ]
    
env:
  VERSION: 1.1.${{ github.run_number }}

jobs:
  BuildApk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1    
      
      - run: flutter build apk --build-name=${{ env.VERSION }} --build-number=${{ github.run_number }}
        working-directory: ./circle #TODO
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: apk
          path: ./circle/build/app/outputs/flutter-apk/app-release.apk #TODO
          
  BuildAab:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
    
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1        
        
      - run: flutter build appbundle --build-name=${{ env.VERSION }} --build-number=${{ github.run_number }}
        working-directory: ./circle
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: aab
          path: ./circle/build/app/outputs/bundle/release/app-release.aab #TODO
      
          
  ReleaseToGithub:
    needs: BuildApk    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: apk
          path: .

      - name: release
        uses: actions/create-release@v1
        id: circle_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: Circle_V_${{ env.VERSION }}
          body_path: ./Changelog.md #TODO
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.circle_release.outputs.upload_url }}
          asset_path: ./app-release.apk
          asset_name: circle.apk
          asset_content_type: application/apk
          
          
  # ReleaseToAppCenter:
  #   needs: BuildAab
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     #- uses: actions/checkout@v3
    
  #     - name: Download a Build Artifact
  #       uses: actions/download-artifact@v3.0.0
  #       with:
  #         name: aab
  #         path: .
          
  #     - name: App Center Distribute
  #       uses: devussy/AppCenter-Distribute-Github-Action@v1.0.2
  #       with:
  #         # App name followed by username e.g. devussy/Sample-App
  #         app: lna-dev/Circle
  #         # Upload token - you can get one from appcenter.ms/settings
  #         token: ${{ secrets.APP_CENTER_TOKEN }}
  #         # Distribution group
  #         group: Collaborators
  #         # Artifact to upload (.apk or .ipa)
  #         file: ./app-release.aab
  #         # Release notes visible on release page
  #         #releaseNotes: Changelog.md
  #         silent: false
      
